version: '3.7'

services:

  selenium-horoscope:
    image: selenium/standalone-chrome
    container_name: selenium-horoscope
    shm_size: "2gb"

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: horoscope-bot
    volumes:
      - ./:/root/Horoscope/
      - ./cache-doctr:/root/.cache/doctr/
    container_name: horoscope
    depends_on:
      - "selenium-horoscope"

